services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: jobpassword
      POSTGRES_DB: jobservice
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
